[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/public/**"]